#!/bin/sh
### BEGIN INIT INFO
# Provides:          raasmanagerservice
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This is the RaaS Manager Website
### END INIT INFO

SERVICE_NAME=raasmanagerservice
APP_DEPLOYMENT_DIR=/var/aspnetcore/raasmanager/

PIDFILE=/var/run/$SERVICE_NAME.pid
LOGFILE=/var/log/$SERVICE_NAME.log

log(){
  echo "INFO:  $(date): ${*}"
}

warn(){
  echo "WARN:  $(date): ${*}"
}

err(){
  echo "ERROR: $(date): ${*}"
}

die(){
  echo "FATAL: $(date): ${*} - exiting ..."
  exit 1
}

start() {
  if [ -f $PIDFILE ] && [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    warn 'Service already running' >&2
    return 1
  fi
  log 'Starting service…' >&2

  . /etc/profile
  cd $APP_DEPLOYMENT_DIR
  
  # creating log folder
  mkdir -p /var/log/raasmanager 
  
  ./OFX.RAASManager --port=60000 &> $LOGFILE & echo $! > $PIDFILE
 
  sleep 2
  PID=$(cat $PIDFILE)
    if pgrep -f $SERVICE_NAME > /dev/null
    then
      log "$SERVICE_NAME is now running, the PID is $PID"
    else
      err ''
      err "Error! Could not start $SERVICE_NAME!"
    fi
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    warn 'Service not running' >&2
    return 1
  fi
  log 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  log 'Service stopped' >&2
}

status() {
    printf "%-50s" "Checking $SERVICE_NAME..."
    if [ -f $PIDFILE ] && [ -s $PIDFILE ]; then
        PID=$(cat $PIDFILE)
            if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
                printf "%s\n" "The process appears to be dead but pidfile still exists"
            else    
                log "Running, the PID is $PID"
            fi
    else
        printf "%s\n" "Service not running"
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
esac
